---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-action
  labels:
    app: action-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-server
  template:
    metadata:
      labels:
        app: action-server
    spec:
      containers:
      - name: private-rasa-os-img
        image: naaz22/rasa-test:action
        ports:
          - containerPort: 5055
        command: ["rasa", "run", "actions","--port", "5055"]
      
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-action
spec:
  ports:
    - port: 5055
      targetPort: 5055
  selector:
    app: action-server
  type: LoadBalancer
