---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: private-rasa-os-img
        image: naaz22/rasa-test:frontend
        ports:
          - containerPort: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-ui
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: ui
  type: LoadBalancer
